#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/bin/cli" "$@"
  ret=$?
else
  node  "$basedir/bin/cli" "$@"
  ret=$?
fi
exit $ret
