name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    name: typecheck (node ${{ matrix.node }}, typescript ${{ matrix.typescript }})

    strategy:
      matrix:
        node: [lts/*]
        # Based on https://majors.nullvoxpopuli.com/q?minors=on&packages=typescript
        typescript: ["5.4"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Set typescript ${{ matrix.typescript }}
        run: pnpm add --save-dev typescript@${{ matrix.typescript }} && npx tsc --version

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ${{ matrix.os }}
    name: test (os ${{ matrix.os }}, node ${{ matrix.node }})

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [lts/*]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Unit
        run: pnpm unit

      - name: Build
        run: pnpm build
